export type AuditCase = {
  text: string;
  expectEmergency: boolean;
  answers?: Record<string, string>;
};

export const auditCases: AuditCase[] = [
  // Emergency phrases
  { text: "severe bleeding that will not stop", expectEmergency: true },
  { text: "I cannot breathe properly", expectEmergency: true },
  { text: "chest pain is crushing", expectEmergency: true },
  { text: "my father collapsed and is not waking up", expectEmergency: true },
  { text: "my child has a high fever and is fitting", expectEmergency: true },
  { text: "my face is swollen and my throat is closing", expectEmergency: true },
  { text: "one side of my face is drooping", expectEmergency: true },
  { text: "I took a whole packet of paracetamol", expectEmergency: true },
  { text: "I want to kill myself", expectEmergency: true },
  { text: "I am coughing up blood", expectEmergency: true },
  { text: "tightness in chest when I walk", expectEmergency: true },
  { text: "I swallowed a chemical", expectEmergency: true },
  { text: "water is coming out of my pregnant belly", expectEmergency: true },
  { text: "I am pregnant and bleeding", expectEmergency: true },
  { text: "I feel dizzy and I am about to faint", expectEmergency: true },
  { text: "my speech is slurred and my arm is weak", expectEmergency: true },
  { text: "blood in my vomit", expectEmergency: true },
  { text: "my throat is swelling and I cannot breathe through my throat", expectEmergency: true },
  { text: "my son is fitting again", expectEmergency: true },
  { text: "I drank bleach by mistake", expectEmergency: true },
  { text: "poisoning, my child drank kerosene", expectEmergency: true },
  { text: "overdose on my tablets", expectEmergency: true },
  { text: "I am bleeding from my nose and it will not stop", expectEmergency: true },
  { text: "blood in my stool since yesterday", expectEmergency: true },
  { text: "sudden confusion and I cannot lift my arm", expectEmergency: true },
  { text: "the man is unresponsive", expectEmergency: true },
  { text: "severe allergic reaction after eating peanuts", expectEmergency: true },
  { text: "I am struggling to breathe", expectEmergency: true },

  // Routine symptoms that must NOT be flagged as emergencies
  { text: "I have a fever", expectEmergency: false },
  { text: "fever and headache since yesterday", expectEmergency: false },
  { text: "I have a cough for two weeks", expectEmergency: false },
  { text: "mild headache in the afternoon", expectEmergency: false },
  { text: "my stomach hurts badly on the right side", expectEmergency: false },
  { text: "I have diarrhoea since morning", expectEmergency: false },
  { text: "I fell and my arm is bent strangely", expectEmergency: false },
  { text: "I am so tired I cannot walk", expectEmergency: false },
  { text: "itchy rash on my arms", expectEmergency: false },
  { text: "sore throat and runny nose", expectEmergency: false },
  { text: "my back hurts after lifting a bag", expectEmergency: false },
  { text: "I feel dizzy when I stand up", expectEmergency: false },
  { text: "my eyes are yellow and my urine is dark", expectEmergency: false },
  { text: "my leg is swollen and red and hot", expectEmergency: true },
  { text: "I cannot sleep at night", expectEmergency: false },
  { text: "my baby is crying a lot", expectEmergency: false },
  { text: "toothache for three days", expectEmergency: false },
  { text: "I have a mild rash on my neck", expectEmergency: false },
  { text: "my eyes hurt from the sun", expectEmergency: false },
  { text: "I am short of breath when climbing stairs", expectEmergency: false },
  { text: "period pain", expectEmergency: false },
  { text: "I keep sneezing", expectEmergency: false },
  { text: "mild stomach discomfort after eating", expectEmergency: false },
  { text: "my knee is stiff in the morning", expectEmergency: false },
  { text: "I have a headache that keeps coming back", expectEmergency: false },
  { text: "itchy eyes", expectEmergency: false },
  { text: "my wrist hurts from typing", expectEmergency: false },
  { text: "a lump in my breast", expectEmergency: false },
  { text: "I have been vomiting once", expectEmergency: false },
  { text: "my child has a mild cough", expectEmergency: false },
  { text: "I feel hot but I am not sure", expectEmergency: false },
  { text: "sore muscles after work", expectEmergency: false },
  { text: "my nose is blocked", expectEmergency: false },
  { text: "I am constipated", expectEmergency: false },
  { text: "my ear hurts", expectEmergency: false },
  { text: "I have a small wound on my leg", expectEmergency: false },
  { text: "mild burning when I urinate", expectEmergency: false },
  { text: "I am tired after farming", expectEmergency: false },
  { text: "my hands shake a little", expectEmergency: false },
  { text: "I keep forgetting small things", expectEmergency: false },
  { text: "my jaw hurts when I chew", expectEmergency: false },
  { text: "a red spot on my leg that is warm", expectEmergency: false },
  { text: "I sneeze when I am near dust", expectEmergency: false },
  { text: "my period is late", expectEmergency: false },
  { text: "I feel bloated after meals", expectEmergency: false },
  { text: "my tongue tastes strange", expectEmergency: false },
  { text: "I have a small cut on my hand", expectEmergency: false },
  { text: "itchy scalp", expectEmergency: false },
  { text: "mild stomach pain after eating spicy food", expectEmergency: false },
  { text: "I sweat at night", expectEmergency: false },
  { text: "my voice is hoarse", expectEmergency: false },
  { text: "I cannot finish my sentence", expectEmergency: false },
  { text: "dizziness when I stand up quickly", expectEmergency: false },
  { text: "I have a mild headache every afternoon", expectEmergency: false },
  { text: "a boil on my thigh", expectEmergency: false },
  { text: "my chest feels tight when I am anxious", expectEmergency: false },
  { text: "I am hungry all the time", expectEmergency: false },
  { text: "my vision is a bit blurry", expectEmergency: false },
  { text: "my child is not eating well", expectEmergency: false },
  { text: "I bruise easily", expectEmergency: false },
  { text: "my feet are swollen in the evening", expectEmergency: false },
  { text: "I have a mild skin infection", expectEmergency: false },
  { text: "my urine is darker than usual", expectEmergency: false },
  { text: "I have been sneezing all week", expectEmergency: false },

  // Unclear input must not produce a diagnosis or emergency
  { text: "I do not feel well", expectEmergency: false },
  { text: "something is wrong", expectEmergency: false },
  { text: "help", expectEmergency: false },
  { text: "I am not sure what is happening", expectEmergency: false },
  { text: "it hurts", expectEmergency: false },
  { text: "I feel strange", expectEmergency: false },
  { text: "the baby is crying", expectEmergency: false },
  { text: "I ate something bad", expectEmergency: false },
  { text: "my body is hot", expectEmergency: false },
  { text: "I need medicine", expectEmergency: false },

  // Body ache, kept separate from fever
  { text: "I have leg ache", expectEmergency: false },
  { text: "my shoulder is aching", expectEmergency: false },
  { text: "body ache all over", expectEmergency: false },
  { text: "my back is paining", expectEmergency: false },
  { text: "my hand hurts", expectEmergency: false },
  { text: "joint pain", expectEmergency: false },
  { text: "muscle pain", expectEmergency: false },
  { text: "my knees ache", expectEmergency: false },
  { text: "I have wrist pain", expectEmergency: false },
  { text: "I have a fever", expectEmergency: false },

  // Body ache that is genuinely urgent
  { text: "I cannot move my leg", expectEmergency: true },
  { text: "my leg is cold and pale", expectEmergency: true },
  { text: "my knee is hot and swollen", expectEmergency: true },
  { text: "chest pain spreading to my arm", expectEmergency: true }
];
