export type ReviewSummaryInput = {
  patientName: string;
  symptomText: string;
  possibleCauses: string[];
  urgency: string;
  emergency: boolean;
};

export function buildReviewSummary(input: ReviewSummaryInput): string {
  const lines: string[] = [];
  lines.push(`Review request from ${input.patientName || "a Rural Help patient"}.`);
  lines.push(`Reported in own words: "${input.symptomText.trim()}"`);
  if (input.possibleCauses.length > 0) {
    lines.push("Possible causes listed by Rural Help (not a diagnosis):");
    for (const cause of input.possibleCauses) {
      lines.push(`- ${cause}`);
    }
  }
  if (input.emergency) {
    lines.push("Warning signs were present in this conversation, so emergency guidance was shown to the patient.");
  }
  lines.push(`Urgency level from Rural Help: ${input.urgency}.`);
  lines.push(
    "This summary was generated by Rural Help as information only. It is not a diagnosis and the cause has not been confirmed. Please assess the patient directly."
  );
  return lines.join("\n");
}
